### DISCUSSION TITLE
Custom linter overrides analysis_options?

### DISCUSSION THREAD

**Discussion by kyeshmz** [mono0926/pedantic_mono#7] [Q&A]
Hi, thanks for the great package.
Its not such a big deal as I know just use solely the lining that this package provides, but it seems like any custom linting rules overrides the imported rules, making them not able to coexist.

This is just a sample, but the linting does not work for things such as awaitfutures when a custom rule is applied.

```
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true

linter:
  rules:
    lines_longer_than_80_chars: 120

```

**Comment by mono0926** [comment]
This is not directly related to `pedantic_mono`.

You can change line length by this:

```yaml
linter:
  rules:
    lines_longer_than_80_chars: false
```

and https://stackoverflow.com/a/62873926 if needed.

If you want to know more, ask at https://stackoverflow.com.
