### ISSUE TITLE
required pendatic for using pedantic_mono

### ISSUE THREAD

**Issue by skzwksk** [mono0926/pedantic_mono#2]
It is written in README 
```
dev_dependencies:
  pedantic_mono: any
```

So, I tried above. but, it has occurred this error.

```
$flutter analyze
warning • The include file package:pedantic/analysis_options.yaml in
       ~/.pub-cache/hosted/pub.dartlang.org/pedantic_mono-1.8.0/lib/analysis_options_flutter_samples.yaml cannot be found • analysis_options.yaml:1:11 •
       include_file_not_found

1 issue found. (ran in 2.0s)
```

So I fixed pubspec.yaml this

```
dev_dependencies:
  pedantic: ^1.9.0
  pedantic_mono: 1.8.0
```

Then, it is fixed.
```
$flutter analyze

No issues found! (ran in 2.0s)
```

please update readme

**Comment by mono0926** [comment]
I suspect that it is your environment problem (related to cache?).

I confirmed that `pedantic` is installed transitively with simple project: [example.zip](https://github.com/mono0926/pedantic_mono/files/4607724/example.zip)

pubspec.yaml:

```yaml
dev_dependencies:
  pedantic_mono:
```

pubspeck.lock:

```yaml
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.0"
  pedantic_mono:
    dependency: "direct dev"
    description:
      name: pedantic_mono
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.0"
```

---

```sh
❯ dart --version
Dart VM version: 2.8.1 (stable) (Thu Apr 30 09:25:21 2020 +0200) on "macos_x64"
```
