### ISSUE TITLE
Custom linter overrides analysis_options?

### ISSUE THREAD

**Issue by kyeshmz** [mono0926/pedantic_mono#6]
Hi, thanks for the great package.
Its not such a big deal as I know just use solely the lining that this package provides, but it seems like any custom linting rules overrides the imported rules, making them not able to coexist.

This is just a sample, but the linting does not work for things such as awaitfutures when a custom rule is applied.

```
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true

linter:
  rules:
    lines_longer_than_80_chars: 120

```
